// tests/testData.js

const validData = [
  [
    // rawData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    // expectedRawData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    // expectedProcessedData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      debt: 20,
      EBIT: 1180,
      ROCE: 0.13082039911308205,
      PE: 6,
    },
    // expectedQuantitativeDecision
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      ROCEscore: 0.02180339985218034,
      PEscore: 4.208295253536264,
      PE_assessment: "Company's PE ratio is Good",
      ROCE_assessment: "Company's ROCE ratio is Poor",
    },
    // expectedReport
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
  ],
  [
    // rawData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    // expectedRawData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    // expectedProcessedData
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      debt: 20,
      EBIT: 1180,
      ROCE: 0.13082039911308205,
      PE: 6,
    },
    // expectedQuantitativeDecision
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      ROCEscore: 0.02180339985218034,
      PEscore: 4.208295253536264,
      PE_assessment: "Company's PE ratio is Good",
      ROCE_assessment: "Company's ROCE ratio is Poor",
    },
    // expectedReport
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
  ],
];

const inValidData = [
  [
    {
      // Missing companyName
      companyID: "MyCompanyID002",
      sector: "Finance",
      financialYear: 2025,
      marketCapital: 200000,
      stockPrice: 10,
    },
  ],
];

export default { validData, inValidData };
