const validData = {
  rawData: [
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    {
      companyName: "MyCompany2",
      companyID: "MyCompanyID002",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 200000,
      stockPrice: 15,
      profit: 2500,
      EPS: 3,
      equity: 11000,
      outstandingShares: 1200,
      interestIncome: 80,
      tax: 30,
      interestExpense: 20,
      currentLeasePayable: 10,
      currentOtherFinancialLiabilities: 10,
      nonCurrentLeasePayable: 8,
      nonCurrentOtherFinancialLiabilities: 7,
    },
    {
      companyName: "MyCompany3",
      companyID: "MyCompanyID003",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 180000,
      stockPrice: 10,
      profit: 1000,
      EPS: 1.8,
      equity: 9500,
      outstandingShares: 950,
      interestIncome: 70,
      tax: 20,
      interestExpense: 10,
      currentLeasePayable: 4,
      currentOtherFinancialLiabilities: 6,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 6,
    },
    {
      companyName: "MyCompany4",
      companyID: "MyCompanyID004",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 220000,
      stockPrice: 18,
      profit: 3000,
      EPS: 4,
      equity: 12500,
      outstandingShares: 1300,
      interestIncome: 90,
      tax: 28,
      interestExpense: 25,
      currentLeasePayable: 8,
      currentOtherFinancialLiabilities: 12,
      nonCurrentLeasePayable: 9,
      nonCurrentOtherFinancialLiabilities: 8,
    },
  ],
  expectedData: [
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    {
      companyName: "MyCompany2",
      companyID: "MyCompanyID002",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 200000,
      stockPrice: 15,
      profit: 2500,
      EPS: 3,
      equity: 11000,
      outstandingShares: 1200,
      interestIncome: 80,
      tax: 30,
      interestExpense: 20,
      currentLeasePayable: 10,
      currentOtherFinancialLiabilities: 10,
      nonCurrentLeasePayable: 8,
      nonCurrentOtherFinancialLiabilities: 7,
    },
    {
      companyName: "MyCompany3",
      companyID: "MyCompanyID003",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 180000,
      stockPrice: 10,
      profit: 1000,
      EPS: 1.8,
      equity: 9500,
      outstandingShares: 950,
      interestIncome: 70,
      tax: 20,
      interestExpense: 10,
      currentLeasePayable: 4,
      currentOtherFinancialLiabilities: 6,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 6,
    },
    {
      companyName: "MyCompany4",
      companyID: "MyCompanyID004",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 220000,
      stockPrice: 18,
      profit: 3000,
      EPS: 4,
      equity: 12500,
      outstandingShares: 1300,
      interestIncome: 90,
      tax: 28,
      interestExpense: 25,
      currentLeasePayable: 8,
      currentOtherFinancialLiabilities: 12,
      nonCurrentLeasePayable: 9,
      nonCurrentOtherFinancialLiabilities: 8,
    },
  ],
};

const inValidData = [
  {
  test:'Fetching duplicate by CompanyID',
  rawData: [
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: null,
      stockPrice: null,
      profit: null,
      EPS: null,
    },
  ],
  expectedData: [
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
    {
      companyName: "MyCompany1",
      companyID: "MyCompanyID001",
      sector: "Software",
      financialYear: 2025,
      marketCapital: 150000,
      stockPrice: 12,
      profit: 1200,
      EPS: 2,
      equity: 9000,
      outstandingShares: 1000,
      interestIncome: 60,
      tax: 25,
      interestExpense: 15,
      currentLeasePayable: 5,
      currentOtherFinancialLiabilities: 5,
      nonCurrentLeasePayable: 5,
      nonCurrentOtherFinancialLiabilities: 5,
    },
  ],
}
];

export default { validData, inValidData };
